### ISSUE TITLE
Forsendur um smit í elstu hópunum

### ISSUE THREAD

**Issue by vthorsteinsson** [bgautijonsson/covid19#1]
Sæll Brynjólfur Gauti, og takk fyrir þessa vinnu. Ég er aðallega að velta fyrir mér forsendum í elstu aldurshópunum. Elstu aldurshóparnir eru sem kunnugt er í langmestri hættu, bæði líklegastir til að þurfa innlögn á sjúkrahús, gjörgæslu, öndunarvélar og svo er dánartíðni þar miklu hærri en í öðrum hópum. Mikið veltur því á að forsendur þar séu réttar og a.m.k. að reiknað sé með rúmum öryggismörkum í þeim hópi. Í raungögnunum í líkaninu þínu er enginn í 80+ aldurshópnum sem hefur smitast (reyndar kominn einn inn í raungögnin í dag) og fáir í 70-79. Þú "bætir upp" skortinn í 80+ með því að leggja eitt tilfelli við hvern aldurshóp. Það er forsenda sem þarf að undirbyggja betur fyrir áframhaldandi líkanasmíð og spár. Það mætti til dæmis skoða smitprósentur í þessum aldurshópum í öðrum löndum svipuðum Íslandi með stærri þýði. Einnig væri hægt að gera líkan sem byggir á aldursdreifingu landsmanna og áætlaðri smithættu í hverjum aldurshópi. En, allavega, mig grunar að um leið og forsendan um 0,29% smita í 80+ hópnum hækkar, sértu fljótlega kominn í mun hærri tölur um spítalavist og dauðsföll, því miður. Eða er ég á villigötum með þessar spekúleringar?

**Comment by haraldur68** [comment]
Daginn.  Bestu þakkir fyrir líkanið.  Fróðlegt.  Ég skil það svo að það sé still með gögnum frá Hubei og S-Kóreu og þau ákvarði í raun toppinn.  Er það rétt skilið?  Ef svo er vakna spurningar um mismun á sóttvörnum á Íslandi og t.d. í Hubei, en þar var fyrst allt í lausung, en svo skellt harkalega í lás.

**Comment by bgautijonsson** [comment]
Mjög góðar ábendingar, @vthorsteinsson, þetta er á verkefnalistanum. 

@haraldur68 líkanið sem nú er notað á covid.hi.is notaði eingöngu gögn um Ísland, en nú notum við stigskipt bayesískt líkan sem nýtir upplýsingar um önnir lönd. líkanið er hér: https://github.com/bgautijonsson/covid19/blob/master/Stan/Logistic/Hierarchical_Logistic_Cases.stan

Við erum að vinna í að uppfæra github síðuna með kóða og llýsingum yfir helgina.

**Comment by haraldur68** [comment]
Væri ekki rétt að bæta við fjölda dauðsfalla?  Aldursdreifing smitaðra á Íslandi gefur tilefni til töluverðar bjartsýni, en nú eru sjálfsagt einhverjir að nota ítalskt hlutfall látinna og fá mjög háar tölur.

**Comment by bgautijonsson** [comment]
@haraldur68, þetta er líka í vinnslu.

**Comment by haraldur68** [comment]
Þökk.  Hverjar eru breytistærðirnar sem fara inn í líkanið og hvernig ákvarðast topppunkturinn?  Væri ekki snjallt að keyra þetta með mismunandi gildum á helstu breytistærðum?

**Comment by hjaltisig74** [comment]
Er mannfjöldi á Íslandi eða Reykjavík parameter í líkaninu?
Hver er hemillinn sem ræður því að útbreiðsla stöðvast þegar nokkur hundruð manns eru smituð?

**Comment by bgautijonsson** [comment]
Sjáið endilega tæknilega skýrslu hér í bili: https://rpubs.com/bgautijonsson/588811

Ætla að loka þessu issue því margar mismunandi spurningar. Gerið ný issue ef fleiri spurningar vakna eftir lestur.
