### ISSUE TITLE
SIR-type model for Iceland?

### ISSUE THREAD

**Issue by martinvoigt** [bgautijonsson/covid19#2]
As I mentioned before, with Iceland still being in an early stage of the outbreak, why rely only on logistic growth models, which tend to underestimate total infections at such early points (before the inflection point is reached) - this is for example mentioned in the Wu et al. paper? Countries in Europe are still in the same situation, and other countries that see a decline implemented way stronger measures and were in different situations, so not sure how much the model will improve if it is calibrated on such countries?

Why not add a simple SIR-type model adapted for Iceland? This should be quite easy to implement - there is already a number of covid-19 specific SIR models from various labs to be used online (https://neherlab.org/covid19/, see screenshots for an example of an Iceland-adapted version at http://covid.scicorner.com/) which are mostly also available on GitHub...

![localhost_3000__%7B%22population%22%3A%7B%22populationServed%22%3A364200%2C%22country%22%3A%22Iceland%22%2C%22hospitalBeds%22%3A1169%2C%22ICUBeds%22%3A29%2C%22suspectedCasesToday%22%3A40%2C%22importsPerDay%22%3A0%](https://user-images.githubusercontent.com/36659258/77306325-68d51500-6cef-11ea-8f30-0d98b3d54037.png)

**Comment by bgautijonsson** [comment]
Thank you, Martin, for the material. Fitting an S(E)IR model has been on our list. We have recently gotten more personnel who will concentrate on such models. Please continue to send us recommendations if you have more.

**Comment by martinvoigt** [comment]
Feel free to have a look at http://covid.scicorner.com/ which is a version of the [Neher lab model](https://neherlab.org/covid19/) with some added "default" values for Iceland and the most up to date case numbers...

By default, I changed the "Confirmed (% total)" values in the age-specific input table, so that they are based on the current age distribution of confirmed cases on covid.is/data: For each age group, the number is calculated as (confirmed cases)/(total population in age group), normalized to an average number of 40 %. I'm sure these age-specific info for Iceland could be improved further though...

A nice aspect of this model implementation is though that everyone can play around & test the potential effect of different levels of mitigation!

**Comment by hreinnbeck** [comment]
I've been maintaining a fork for the last week, updated daily: https://covid.vafri.is/

Source: https://github.com/hreinnbeck/covid19_scenarios
I'll sync to my local changes in a few hours, the repo is out of sync for a few days.

**Comment by martinvoigt** [comment]
> Source: https://github.com/hreinnbeck/covid19_scenarios
> I'll sync to my local changes in a few hours, the repo is out of sync for a few days.

Great! Mine is at https://github.com/martinvoigt/covid19_scenarios :)

**Comment by bgautijonsson** [comment]
Thanks for the help guys. We have part of our team focusing on SIR models now.

**Comment by tryggvigy** [comment]
I've added a parser (using landlaeknir doc as a data source) for Iceland in the covid19_scenarios model discussed in the thread. If your team is developing a SIR model I hope it can be useful to compare results with. [Link](https://neherlab.org/covid19/?%7B%22population%22%3A%7B%22populationServed%22%3A364260%2C%22country%22%3A%22Iceland%22%2C%22hospitalBeds%22%3A1169%2C%22ICUBeds%22%3A29%2C%22suspectedCasesToday%22%3A53%2C%22importsPerDay%22%3A0.1%2C%22cases%22%3A%22Iceland%22%7D%2C%22epidemiological%22%3A%7B%22r0%22%3A2.7%2C%22latencyTime%22%3A5%2C%22infectiousPeriod%22%3A3%2C%22lengthHospitalStay%22%3A4%2C%22lengthICUStay%22%3A14%2C%22seasonalForcing%22%3A0.2%2C%22peakMonth%22%3A0%2C%22overflowSeverity%22%3A2%7D%2C%22simulation%22%3A%7B%22simulationTimeRange%22%3A%7B%22tMin%22%3A%222020-03-01T00%3A00%3A00.000Z%22%2C%22tMax%22%3A%222020-09-01T00%3A00%3A00.000Z%22%7D%2C%22numberStochasticRuns%22%3A0%7D%2C%22containment%22%3A%5B%7B%22t%22%3A%222020-03-01T00%3A00%3A00.000Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-03-21T10%3A40%3A00.000Z%22%2C%22y%22%3A0.500639658848614%7D%2C%7B%22t%22%3A%222020-04-10T21%3A20%3A00.000Z%22%2C%22y%22%3A0.4%7D%2C%7B%22t%22%3A%222020-05-01T08%3A00%3A00.000Z%22%2C%22y%22%3A0.4%7D%2C%7B%22t%22%3A%222020-05-21T18%3A40%3A00.000Z%22%2C%22y%22%3A0.4%7D%2C%7B%22t%22%3A%222020-06-11T05%3A20%3A00.000Z%22%2C%22y%22%3A0.4%7D%2C%7B%22t%22%3A%222020-07-01T16%3A00%3A00.000Z%22%2C%22y%22%3A0.4%7D%2C%7B%22t%22%3A%222020-07-22T02%3A40%3A00.000Z%22%2C%22y%22%3A0.4%7D%2C%7B%22t%22%3A%222020-08-11T13%3A20%3A00.000Z%22%2C%22y%22%3A0.45%7D%2C%7B%22t%22%3A%222020-09-01T00%3A00%3A00.000Z%22%2C%22y%22%3A0.45%7D%5D%2C%22current%22%3A%7B%22overall%22%3A%22Custom%22%2C%22population%22%3A%22Iceland%22%2C%22epidemiological%22%3A%22Custom%22%2C%22containment%22%3A%22Custom%22%7D%7D)
