### ISSUE TITLE
Authentication for googlesheet4 not necessary.

### ISSUE THREAD

**Issue by blitzkopf** [bgautijonsson/covid19#5]
As the google sheet used in the code is public it is not necessary to authenticate against google every time. 
Instead of 
`sheets_auth(email = "bgautijonsson@gmail.com")
`
you could use  
`sheets_deauth()`
That way you do not need to have a browser session to do the authentication.

**Comment by tryggvigy** [comment]
You can also fetch the csv files directly via url

Smit:
https://docs.google.com/spreadsheets/d/1xgDhtejTtcyy6EN5dbDp5W3TeJhKFRRgm6Xk0s0YFeA/export?format=csv&gid=0

Spitali:
https://docs.google.com/spreadsheets/d/1xgDhtejTtcyy6EN5dbDp5W3TeJhKFRRgm6Xk0s0YFeA/export?format=csv&gid=1167203444

Aldur:
https://docs.google.com/spreadsheets/d/1xgDhtejTtcyy6EN5dbDp5W3TeJhKFRRgm6Xk0s0YFeA/export?format=csv&gid=2147090221

**Comment by bgautijonsson** [comment]
Thanks, guys. You are doing god's work.
