### ISSUE TITLE
Suggestions for Landlaeknir google sheet

### ISSUE THREAD

**Issue by tryggvigy** [bgautijonsson/covid19#6]
I'm creating a parser for Iceland in this SRI model https://neherlab.org/covid19/.
I'm using the Landlaeknir Google sheet. It seem to be the most canonical publicly available data on the outbreak in Iceland. Thank you for keeping the data open and accessible!

I've had to [work around](https://github.com/neherlab/covid19_scenarios_data/pull/60#discussion_r399647281) that the date format in "Smit" (mm-dd-YYYY) and "Spitali" (YYYY-mm-dd) are different. Imo YYYY-mm-dd is preferred since it can be sorted chronologically.

What is the status of the Landlaeknir doc? Does landlæknir send you daily updates and you manually fill them into the doc?

How flexible is this doc to change? Could there be a possibility to track ObservedRecovered (batnað)?

Thanks a lot for the great work you folks are doing.

**Comment by tryggvigy** [comment]
I can see that batnað is tracked now in the document. The date discrepancy still stands but I'll close the issue

**Comment by bgautijonsson** [comment]
Hi, Tryggvi. I am a google drive noob, but I think I fixed the dates. Thanks for the suggestions
